import type { IncidentDTO } from '@/types/IncidentDTO'

export const MOCK_INCIDENTS: IncidentDTO[] = [
  {
    id: 'INC-1001',
    title: 'Checkout service unavailable',
    description: 'Users cannot complete purchases due to 502 errors from the checkout service.',
    severity: 'Critical',
    status: 'Open',
    service: {
      id: 'svc-checkout',
      name: 'Checkout Service',
    },
    createdAt: '2026-01-08T08:15:00Z',
    updatedAt: '2026-01-08T08:15:00Z',
    assignee: null,
  },
  {
    id: 'INC-1002',
    title: 'Delayed email notifications',
    description: 'Transactional emails are being sent with significant delays.',
    severity: 'High',
    status: 'InProgress',
    service: {
      id: 'svc-notifications',
      name: 'Notification Service',
    },
    createdAt: '2026-01-08T07:40:00Z',
    updatedAt: '2026-01-08T08:10:00Z',
    assignee: {
      id: 'usr-1',
      displayName: 'Alice Jensen',
    },
  },
  {
    id: 'INC-1003',
    title: 'Search results incomplete',
    description: 'Some products are missing from search results due to indexing lag.',
    severity: 'Medium',
    status: 'Acknowledged',
    service: {
      id: 'svc-search',
      name: 'Search Service',
    },
    createdAt: '2026-01-08T06:55:00Z',
    updatedAt: '2026-01-08T07:20:00Z',
    assignee: {
      id: 'usr-2',
      displayName: 'Brian Thomsen',
    },
  },
  {
    id: 'INC-1004',
    title: 'User profile updates failing',
    description: 'Profile changes are not being saved for some users.',
    severity: 'High',
    status: 'InProgress',
    service: {
      id: 'svc-user',
      name: 'User Service',
    },
    createdAt: '2026-01-08T05:30:00Z',
    updatedAt: '2026-01-08T06:45:00Z',
    assignee: {
      id: 'usr-3',
      displayName: 'Clara Madsen',
    },
  },
  {
    id: 'INC-1005',
    title: 'Slow product page loading',
    description: 'Product detail pages are loading slowly due to high database load.',
    severity: 'Medium',
    status: 'Open',
    service: {
      id: 'svc-catalog',
      name: 'Product Catalog',
    },
    createdAt: '2026-01-08T04:10:00Z',
    updatedAt: '2026-01-08T04:10:00Z',
    assignee: null,
  },
  {
    id: 'INC-1006',
    title: 'Payment provider timeout',
    description: 'External payment provider is timing out intermittently.',
    severity: 'Critical',
    status: 'InProgress',
    service: {
      id: 'svc-payments',
      name: 'Payment Gateway',
    },
    createdAt: '2026-01-08T03:50:00Z',
    updatedAt: '2026-01-08T08:05:00Z',
    assignee: {
      id: 'usr-4',
      displayName: 'David Holm',
    },
  },
  {
    id: 'INC-1007',
    title: 'Analytics data missing',
    description: 'Some tracking events are not being recorded in the analytics pipeline.',
    severity: 'Low',
    status: 'Acknowledged',
    service: {
      id: 'svc-analytics',
      name: 'Analytics Service',
    },
    createdAt: '2026-01-07T23:30:00Z',
    updatedAt: '2026-01-08T01:00:00Z',
    assignee: {
      id: 'usr-2',
      displayName: 'Brian Thomsen',
    },
  },
  {
    id: 'INC-1008',
    title: 'Mobile app login failures',
    description: 'Some mobile users cannot log in due to token validation errors.',
    severity: 'High',
    status: 'Open',
    service: {
      id: 'svc-auth',
      name: 'Authentication Service',
    },
    createdAt: '2026-01-07T22:15:00Z',
    updatedAt: '2026-01-07T22:15:00Z',
    assignee: null,
  },
  {
    id: 'INC-1009',
    title: 'Background jobs stuck',
    description: 'Several background jobs are not progressing in the queue.',
    severity: 'Medium',
    status: 'InProgress',
    service: {
      id: 'svc-jobs',
      name: 'Job Processing Service',
    },
    createdAt: '2026-01-07T21:05:00Z',
    updatedAt: '2026-01-08T06:00:00Z',
    assignee: {
      id: 'usr-1',
      displayName: 'Alice Jensen',
    },
  },
  {
    id: 'INC-1010',
    title: 'Admin dashboard not loading',
    description: 'The admin dashboard fails to load due to a frontend build error.',
    severity: 'Low',
    status: 'Resolved',
    service: {
      id: 'svc-admin',
      name: 'Admin Portal',
    },
    createdAt: '2026-01-07T19:45:00Z',
    updatedAt: '2026-01-08T02:30:00Z',
    assignee: {
      id: 'usr-3',
      displayName: 'Clara Madsen',
    },
  },
]
